### ISSUE TITLE
用python3运行报错

### ISSUE THREAD

**Issue by 16bh** [lzjun567/crawler_html2pdf#1]
Traceback (most recent call last):
  File "crawler.py", line 56, in parse_url_to_html
    f.write(html)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crawler.py", line 119, in <module>
    main()
  File "crawler.py", line 108, in main
    htmls = [parse_url_to_html(url, str(index) + ".html") for index, url in enumerate(urls)]
  File "crawler.py", line 108, in <listcomp>
    htmls = [parse_url_to_html(url, str(index) + ".html") for index, url in enumerate(urls)]
  File "crawler.py", line 60, in parse_url_to_html
    print(e.message)
AttributeError: 'TypeError' object has no attribute 'message'

**Comment by zh-h** [comment]
`sudo apt-get install tk-dev python-tk `
