### ISSUE TITLE
创建PDF时出错

### ISSUE THREAD

**Issue by nsscc** [lzjun567/crawler_html2pdf#18]
Traceback (most recent call last):
  File "crawler.py", line 165, in <module>
    crawler.run()
  File "crawler.py", line 99, in run
    pdfkit.from_file(htmls, self.name + ".pdf", options=options)
  File "/usr/local/lib/python3.5/dist-packages/pdfkit/api.py", line 49, in from_file
    return r.to_pdf(output_path)
  File "/usr/local/lib/python3.5/dist-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
The switch --outline-depth, is not support using unpatched qt, and will be ignored.Error: This version of wkhtmltopdf is build against an unpatched version of QT, and does not support more then one input document.
Exit with code 1, due to unknown error.

**Comment by nsscc** [comment]
生成的pdf 无 书签

**Comment by yangtao4389** [comment]
试试这个解决方法

>https://itaken.github.io/python/2017/02/18/pdfkit%E9%94%99%E8%AF%AF%E8%B0%83%E8%AF%95.html
