### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by yingxincui** [lzjun567/crawler_html2pdf#33]
python3 crawler.py
Traceback (most recent call last):
  File "crawler.py", line 163, in <module>
    crawler.run()
  File "crawler.py", line 90, in run
    for index, url in enumerate(self.parse_menu(self.request(self.start_url))):
  File "crawler.py", line 116, in parse_menu
    menu_tag = soup.find_all(class_="uk-nav uk-nav-side")[1]
IndexError: list index out of range

**Comment by EricDuy** [comment]
我也遇到了同样的问题，请问你解决了吗？

**Comment by zys864** [comment]
添加headers，修改user-agent
